"""FastAPI application factory and shared server state."""

from __future__ import annotations

import time
from dataclasses import dataclass, field

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from phantom_api.models import MockSpec
from phantom_api.output.dashboard import register_dashboard
from phantom_api.server.middleware import MockControlMiddleware
from phantom_api.server.router_builder import build_routes


@dataclass
class ServerConfig:
    """Runtime configuration for the mock server."""

    delay_ms: int = 0
    cors_origins: list[str] = field(default_factory=lambda: ["*"])
    seed: int | None = None


@dataclass
class ServerState:
    """Mutable state shared across requests for stats and admin control."""

    spec: MockSpec
    config: ServerConfig
    started_at: float = field(default_factory=time.time)
    total_requests: int = 0
    hits: dict[str, int] = field(default_factory=dict)

    def record_hit(self, route_key: str) -> None:
        self.total_requests += 1
        self.hits[route_key] = self.hits.get(route_key, 0) + 1

    def reset(self) -> None:
        self.total_requests = 0
        self.hits.clear()
        self.started_at = time.time()

    def uptime_seconds(self) -> float:
        return round(time.time() - self.started_at, 3)


def create_app(spec: MockSpec, config: ServerConfig | None = None) -> FastAPI:
    """Create a fully-wired FastAPI mock server for ``spec``."""
    config = config or ServerConfig()

    app = FastAPI(
        title=spec.title,
        version=spec.version,
        description=f"Mock server generated by phantom-api from a {spec.source_type} source.",
        docs_url=None,
        redoc_url=None,
    )

    state = ServerState(spec=spec, config=config)
    app.state.mock_state = state

    app.add_middleware(MockControlMiddleware, default_delay_ms=config.delay_ms)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=config.cors_origins,
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    register_dashboard(app, state)
    build_routes(app, spec, state, seed=config.seed)

    return app


def rebuild_routes(app: FastAPI, spec: MockSpec) -> None:
    """Replace the app's mock routes with those from a freshly parsed ``spec``."""
    state: ServerState = app.state.mock_state
    state.spec = spec
    build_routes(app, spec, state, seed=state.config.seed)
